version: "3.10"
services:
  hangman_app:
    container_name: hangman
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
    environment:
      - SERVER_HOST=https://localhost
      - PROJECT_NAME=Hangman
      - SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://user:12345@hangman_app_database:5432/db
      - SQLALCHEMY_MAX_POOL_OVERFLOW=20
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    networks:
      - development

  database:
    container_name: hangman_database
    image: postgres:15
    env_file:
      - db.env
    volumes:
      - postgre:/var/lib/postgresql/data
    networks:
      - development
    ports:
      - "5432:5432"

networks:
  development:


volumes:
  postgre:
